### ISSUE TITLE
Curl error: Peer's Certificate issuer is not recognized.

### ISSUE THREAD

**Issue by jeroen-severein** [forwarder/belco-magento2#5]
Hi,

There appears to be a problem with the cabundle.crt certificate when connecting to https://api.belco.io/ with CURL through the Api class.

The Curl Error occurs here:
vendor/forwarder/belco-magento2/Model/Api.php:208 Belco\Widget\Model\Api::post
vendor/forwarder/belco-magento2/Model/Api.php:127 Belco\Widget\Model\Api::trackEvent
vendor/forwarder/belco-magento2/Model/Api.php:115 Belco\Widget\Model\Api::trackOrder
vendor/forwarder/belco-magento2/Observer/OrderPlacedHook.php:44 Belco\Widget\Observer\OrderPlacedHook::execute

This started occurring on December 21st and still occurs now for every order placed.

Module version: 0.3.2
Magento 2 version: 2.3.2
PHP version: 7.2

**Comment by jeroen-severein** [comment]
Hi, when is https://github.com/forwarder/belco-magento2/pull/6 expected to be merged/released?

**Comment by edwinkruis058** [comment]
@jeroen-severein Doorgevoerd!
